routes/web.php
    Route::resource('quote','Quote\QuoteController');
    Route::post('save_temporary_quote','Quote\HelperController@saveTemporaryQuote');
    Route::post('brokerage_count','Quote\HelperController@brokerage_count');
    Route::post('new_quote_delete_old','Quote\HelperController@action_quote_new');
    Route::get('send_invoice/{id}','Quote\HelperController@sendInvoice');
    Route::get('quotes_draft','Quote\HelperController@quotesDraft');
    Route::post('quotes_publish/{id}',function(\Illuminate\Http\Request $request,$id){
        \App\Quotes::find($id)
            ->update([
                'finish' => 1
            ]);

        return redirect()->route('quote.index')
            ->with('success','publish new quote : success');
    });
    Route::post('save_draft_quote','AjaxController@saveDraft');
    Route::get('quotes_draft_delete/{id}',function($id){
        \App\Quotes::where('id',$id)->update(['is_deleted' => 1]);
        return redirect('quotation/quotes_draft')
            ->with('success','Quote deleted');
    });
    Route::post('get_prorata_days','AjaxController@getProrataDays');
    Route::post('is_approve_quote',function(\Illuminate\Http\Request $request){
        $stats = ['granted','approve'];
        \App\Quotes::find($request->id)
            ->update(['status' => $stats[$request->approve]]);
    });
    Route::get('get_company_assured',function(){
        $data = \App\Insurer::all();
        return response()
            ->json(['data' => $data]);
    });
    Route::post('get_valid_until','AjaxController@getValidUntil');
    Route::post('request_vessel_items','AjaxController@getVesselItems');
    Route::post('request_vessels_detail','AjaxController@getVesselsDetail');
    Route::post('insert_new_vessel','AjaxController@storeVessel');
    Route::prefix('premium')->group(function(){
        Route::get('show_premium_quotes/{id}','Quote\PremiumController@showPremi');
        Route::get('show_premium_quotes_iframe/{id}','Quote\PremiumController@showPremiIframe');
        Route::post('save','Quote\PremiumController@submitQuotePremi');
        Route::post('save_premium_warranty','Quote\PremiumController@submitPremiInstallment');
        Route::get('create_premium_quotes/{id}','Quote\PremiumController@createPremium');
        Route::get('create_premium_warranty/{id}','Quote\PremiumController@createPremiumWarranty');
        Route::post('update_premium_quotes','Quote\PremiumController@updatePremium');
        Route::post('update_premium_quotes_onchange','Quote\PremiumController@updatePremiumOnchange');
        Route::post('create_initial_additional_premium',function(\Illuminate\Http\Request $request){
            $a = \App\QuotesAdditional::create([
                'type_' => '',
                'premium_type' => '',
                'annual_premium' => 0,
                'premium_table_id' => $request->data
            ]);
            return response()
                ->json([
                    'success' => true,
                    'pid' => intval($a->premium_table_id),
                    'id' => $a->id
                ]);
        });
        Route::post('update_hm_premium_quotes','Quote\PremiumController@updateHMPremium');
        Route::post('delete_additional_premium','Quote\PremiumController@deleteAdditionalPremium');
        Route::post('delete_v_premium','Quote\PremiumController@deleteVPremium');
        Route::post('delete_premium_warranty','Quote\PremiumController@deletePremiumWarranty');
    });
});

Route::prefix('inv')->group(function(){
    Route::prefix('notes')->group(function(){
        Route::get('create_credit_note/{id}','CreditNoteController@create');
        Route::post('store_credit_note','CreditNoteController@store');
        Route::get('show/{id}','CreditNoteController@show');
        Route::post('change_credit_note_vessels','CreditNoteController@changeCN');
        Route::post('new_cn_delete_old/{id}','CreditNoteController@NewCNDeleteOld');
    });

    Route::resource('invoice','Invoice\InvoiceController');
    Route::get('create_endorsement/{id}','InvoiceController@createEndorsement');
    Route::post('get_past_endorsement','AjaxController@getVesselPastData');
    Route::post('store_vessel_endorsement','EndorsementController@storeEndorsement');

    Route::get('premi_endorsement/{id}','EndorsementController@premiEndorsement');
    Route::post('update_premium_endorsement','EndorsementController@updatePremium');

    Route::get('endorsements_list','EndorsementController@index');
    Route::get('new_endorsement','EndorsementController@create');
    Route::post('request_data_invoice','AjaxController@reqInvData');
});
/** Sys */
Route::prefix('sys')->group(function(){
    Route::resource('assured','AssuredController');
    Route::get('assured_search',function(){
        $data = \App\Assured::where('assured_name','like','%'.strip_tags($_GET['query']).'%')
            ->where('status',1)
            ->paginate(10);
        return view('pib.assured',compact('data'));
    });
    Route::resource('manage_user','UsersController');
    Route::resource('manage_type','TypeController');
    Route::resource('item_quo','ItemQuoController');
    Route::resource('type_quo','TypeQuoController');
    Route::resource('channel','ChannelController');
    Route::get('channel-search','ChannelController@search');
    Route::resource('coa','CoaController');
    Route::resource('currency','CurrencyController');
    Route::resource('banks','BankController');
    Route::resource('insurer','Insurer\InsurerController');
    Route::prefix('insurer')->group(function(){
        Route::get('vessels/search_rows','VesselController@search');
        Route::post('vessel_detail','Vessel\VesselController@vesselDetail');
        Route::get('vessel_endorsement_view/{id}','EndorsementController@viewEndorsement');
        Route::get('vessel_endorsement_create_detail/{id}','EndorsementController@createVesselEndorsement');
        Route::get('vessel_endorsement_create/{id}','EndorsementController@createEndorsement');
        Route::post('vessel_endorsement_store','EndorsementController@storeEndorsement');
        Route::view('store_endorsement_redirect','pib.vessels.Endorsement.redirect');
        Route::post('check_insured_name','AjaxController@check_insured_name');
    });
});

Route::prefix('voucher')->group(function(){
    Route::resource('premium_receipt_voucher','Voucher\ReceiptVoucherController');
    Route::resource('premium_payment_voucher','Voucher\PaymentVoucherController');
    Route::post('create_premium_payment','Voucher\VoucherController@createPremiumPayment');
    Route::post('request_detail','Voucher\VoucherController@requestDetail');
    Route::post('request_detail_installment','Voucher\VoucherController@requestDetailInstallment');
    Route::get('payment/before-create','Voucher\VoucherController@beforeCreatePV');
    Route::post('payment/get_receipt_voucher','Voucher\VoucherController@getReceiptVoucher');
});

/**
 * Special
 */
Route::prefix('special')->group(function(){
   Route::get('direct-invoice/create','SpecialController@create');
    Route::post('quote-ref-check','SpecialController@quoteRefCheck');
   Route::post('direct-invoice/store','SpecialController@store');
    Route::post('get_insurer_detail','SpecialController@getInsurerDetail');

    Route::get('direct-invoice/premium/{id}','SpecialController@premium');
    Route::get('direct-invoice/installment/{id}','SpecialController@installment');
    Route::post('direct-invoice/installment_go','SpecialController@installment_go');
});

/** Intermediary */
Route::get('intermediary_broker_list','IntermediaryController@brokerList');
Route::get('intermediary_broker_edit/{id}','IntermediaryController@brokerEdit');
Route::get('intermediary_broker_create','IntermediaryController@brokerCreate');
Route::post('intermediary_broker_store','IntermediaryController@brokerStore');
Route::post('intermediary_broker_update','IntermediaryController@brokerUpdate');
Route::get('intermediary_broker_delete/{id}','IntermediaryController@brokerDelete');

Route::get('intermediary_finder_list','IntermediaryController@finderList');
Route::get('intermediary_finder_edit/{id}','IntermediaryController@finderEdit');
Route::get('intermediary_finder_create','IntermediaryController@finderCreate');
Route::post('intermediary_finder_store','IntermediaryController@finderStore');
Route::post('intermediary_finder_update','IntermediaryController@finderUpdate');
Route::get('intermediary_finder_delete/{id}','IntermediaryController@finderDelete');
Route::get('intermediary_list/search_rows','IntermediaryController@search');

/** Company vessel */

Route::post('get_sales_or_marketing',function(\Illuminate\Http\Request $request){
    $data = \App\ChannelGroup::where('type_',$request->channel)
        ->where('status',1)
        ->get();

    return response()
        ->json($data);
});

Route::post('store_new_company_ajax','AjaxController@store_new_company_ajax');


/** Incomes */
Route::get('incomes_list','IncomesController@index');

/** Clients */
Route::get('clients_list','ClientsController@index');
Route::get('create_new_client','ClientsController@createClient');
Route::get('client_edit/{id}','ClientsController@editClient');
Route::post('store_new_client','ClientsController@storeClient');
Route::post('update_client/{id}','ClientsController@updateClient');
Route::post('request_client_insureds','ClientsController@requestClientInsured');
Route::post('clients_list/request_client_insureds','ClientsController@requestClientInsured');

Route::get('clients_list/search_rows','ClientsController@search');

/** Search */

/** Change Password */
Route::view('change-password','pib.change_pass');

Route::get('show_hm_premium_quotes/{id}','ContentController@showHMPremi');
Route::get('show_premium_cargo/{id}','ContentController@showCargoPremi');

Route::post('acc/get_accounting_menu',function(){
   $data = \App\QuoteTypes::whereNotIn('group_name',['QUO','INV'])
       ->get();

    return response()

app/Http/Controllers/Voucher/PaymentVoucherController.php
<?php

namespace App\Http\Controllers\Voucher;

use App\Assured;
use App\Http\Controllers\BaseController;
use App\PaymentVoucher;
use App\PaymentVoucherDetail;
use App\QuotesCommision;
use App\ReceiptVoucher;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PaymentVoucherController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = PaymentVoucher::paginate(30);
        return view('pib.voucher.payment.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(session('premium_receipt_id')){
            $data = ReceiptVoucher::whereIn('id',session('premium_receipt_id'));
            $gross = $data->sum('gross_premium');
            echo $gross;
            print_r(session('premium_receipt_id'));
            $data = $data->get();
            $users = User::all();
            $assured = Assured::findOrFail(session('assured_id'));
            $brokerage = 0;
            foreach ($data as $item) {
                $brokerage = $brokerage + (($item->Commision->brokerage/100) * $item->amount);
            }
            $lastRef = PaymentVoucher::orderBy('id','DESC')
                ->first();
            if($lastRef){
                $splitter = (isset(explode("/",$lastRef->voucher_no)[3])) ? explode("/",$lastRef->voucher_no)[3] : 1;
            }else{
                $splitter = "000";
            }


            $before = '';
            for($i = 0; $i<4 - count(str_split(intval($splitter))); $i++){
                $before .= '0';
            }
            $newRef = 'DBS-PP/'.date('ym').'/'.$before.(intval($splitter) + 1);
            return  view('pib.voucher.payment.create',compact('data','users','assured','gross','brokerage','newRef'));
        }
        return redirect('voucher/payment/before-create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $payment = PaymentVoucher::create([
            'assured_id' => session('assured_id'),
            'voucher_no' => $request->voucher_no,
            'amount' => $request->amount,
            'payment_date' => date('Y-m-d',strtotime($request->payment_date)),
            'bank' => $request->bank,
            'currency' => $request->currency,
            'inception_date' => $request->inception_date,
            'policy_no' => $request->policy_no,
            'gross_premium' => $request->gross_premium,
            'disc_from_insurer' => $request->disc_from_insurer,
            'brokerage' => $request->brokerage,
            'vat' => $request->vat,
            'wht' => $request->wht,
            'others' => $request->others,
            'bank_charge' => $request->bank_charge,
            'net_to_insurer' => $request->net_to_insurer,
            'accounting_entries' => $request->accounting_entries,
            'prepared_by' => $request->prepared_by,
            'approved_by' => $request->approved_by,
            'amount_in_words' => $request->amount_in_words
        ]);

        foreach ($request->receipt_id as $item) {
            PaymentVoucherDetail::updateOrCreate(
                [
                    'payment_voucher_id' => $payment->id,
                    'receipt_voucher_id' => $item
                ],
                [
                    'payment_voucher_id' => $payment->id,
                    'receipt_voucher_id' => $item
                ]
            );
        }

        return redirect()
            ->route('premium_payment_voucher.index')
            ->with('success','Premium payment created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = PaymentVoucher::findOrFail($id);
        return  view('pib.voucher.payment.show',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pib/voucher/payment/before_create.blade.php
@extends('layouts.pib')
@section('content')
        <!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <h4 class="page-title">Select Premium Receipt Voucher</h4>
                <form method="post" id="form-create-" accept-charset="utf-8" action="{{ url('voucher','create_premium_payment') }}">
                    {{ csrf_field() }}
                <div>
                    <div class="col-md-12">
                        <div class="col-md-10">
                            <div class="form-group">
                                <label class="control-label col-md-2">Assured</label>
                                <div class="col-md-6">
                                    <select id="security" name="security" required class="form-control coa" >
                                        @foreach($assured as $ass)
                                            <option value="{{ $ass->id }}">{{ $ass->assured_name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <br>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-2">Periode</label>
                                <div class="col-md-4">
                                    <div class="input-group">
                                        <div class="input-group-addon">From</div>
                                        <input type="date" name="period_from" id="period_from" class="from-control" required>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="input-group">
                                        <div class="input-group-addon">To</div>
                                        <input type="date" name="period_to" id="period_to" class="from-control" required>
                                    </div>
                                </div>
                                <br>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-2">Receipt Voucher</label>
                                <div class="col-md-8">
                                    <a role="button" onclick="getReceiptVoucher()"><span title="Get receipt voucher" class="fa fa-refresh"></span> </a>
                                </div>
                                <br>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                        <table class="table table-bordered data-table" style="display: none;">
                                            <thead>
                                            <tr>
                                                <th class="th-sorting sorting-item"><input type="checkbox" class="checkbox" id="select-all"></th>
                                                <th>Voucher No.</th>
                                                <th>Vessels</th>
                                                <th>Invoice No.</th>
                                                <th>Installment</th>
                                                <th>Amount</th>
                                                <th>Received Date</th>
                                            </tr>
                                            </thead>
                                            <tbody id="_table_list">
                                            </tbody>
                                        </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr><br>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4" style="margin-left: 10px;margin-top: 15px;">
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                </div>
                </form>
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
<!-- /.container-fluid-->
<script>
    function getReceiptVoucher(){
        var from = $("#period_from").val(),
                to = $("#period_to").val(),
                security = $("#security").val();
        if(from == "" || to == "" || security == ""){
            alert('Periksa kembali kolom kolom masukkan!');
            return false;
        }
        $.post(BASE+'/voucher/payment/get_receipt_voucher',{security:security,pfrom:from,pto:to},function(data){
            if(data.success){

                $(".table").css('display','block');
                $.each(data.data,function(i,value){
                    var html = '<tr><td class="th-sorting sorting-item"><input type="checkbox" class="checkbox checkbox-select" name="premium_receipt_id['+i+']" value="'+value.id_+'"></td>';
                    html += '<td>'+value.voucher_no+'</td><td>'+value.quote.vessels+'</td><td>'+value.invoice.invoice_no+'</td><td>'+value.installment.installment_no+' /'+value.invoice.installment_count+'</td>';
                    html += '<td>'+value.amount+'</td><td>'+value.received_date+'</td></tr>';

                    $("#_table_list").append(html);
                })
            }
        })
    }
</script>
@endsection

resources/views/pib/voucher/payment/index.blade.php
@extends('layouts.pib')
@section('content')
        <!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <h3 class="page-title">
                <a type="button" href="{{ url('voucher',['payment','before-create']) }}" class="btn btn-default"><i class="fa fa-plus-square"></i> Create</a>
            </h3>
            <div class="row">
                <div class="col-md-12">
                    <!-- BORDERED TABLE -->
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">Payment Vouchers List</h3>
                        </div>
                        <div class="panel-body">
                            <table class="table table-bordered data-table">
                                <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Insurer</th>
                                    <th>Voucher No.</th>
                                    <th>Amount</th>
                                    <th>Payment Date</th>
                                    <th>Created At</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($data as $i => $d)
                                    <tr>
                                        <td>{{ $i + 1}}</td>
                                        <td>{{ $d->Security->assured_name }}</td>
                                        <td>{{ $d->voucher_no }}</td>
                                        <td>{{ number_format($d->amount) }}</td>
                                        <td>{{ date('d-m-Y',strtotime($d->received_date)) }}</td>
                                        <td>{{ date('d M Y H:i',strtotime($d->created_at)) }} WIB</td>
                                        <td><a href="{{ route('premium_payment_voucher.show',$d->id) }}"><i class="fa fa-eye-slash"></i> </a> </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            {{ $data->render() }}
                        </div>
                    </div>
                    <!-- END BORDERED TABLE -->
                </div>
            </div>
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
@endsection