routes/web.php
    Route::resource('quote','Quote\QuoteController');
    Route::post('save_temporary_quote','Quote\HelperController@saveTemporaryQuote');
    Route::post('brokerage_count','Quote\HelperController@brokerage_count');
    Route::post('new_quote_delete_old','Quote\HelperController@action_quote_new');
    Route::get('send_invoice/{id}','Quote\HelperController@sendInvoice');
    Route::get('quotes_draft','Quote\HelperController@quotesDraft');
    Route::post('quotes_publish/{id}',function(\Illuminate\Http\Request $request,$id){
        \App\Quotes::find($id)
            ->update([
                'finish' => 1
            ]);

        return redirect()->route('quote.index')
            ->with('success','publish new quote : success');
    });
    Route::post('save_draft_quote','AjaxController@saveDraft');
    Route::get('quotes_draft_delete/{id}',function($id){
        \App\Quotes::where('id',$id)->update(['is_deleted' => 1]);
        return redirect('quotation/quotes_draft')
            ->with('success','Quote deleted');
    });
    Route::post('get_prorata_days','AjaxController@getProrataDays');
    Route::post('is_approve_quote',function(\Illuminate\Http\Request $request){
        $stats = ['granted','approve'];
        \App\Quotes::find($request->id)
            ->update(['status' => $stats[$request->approve]]);
    });
    Route::get('get_company_assured',function(){
        $data = \App\Insurer::all();
        return response()
            ->json(['data' => $data]);
    });
    Route::post('get_valid_until','AjaxController@getValidUntil');
    Route::post('request_vessel_items','AjaxController@getVesselItems');
    Route::post('request_vessels_detail','AjaxController@getVesselsDetail');
    Route::post('insert_new_vessel','AjaxController@storeVessel');
    Route::prefix('premium')->group(function(){
        Route::get('show_premium_quotes/{id}','Quote\PremiumController@showPremi');
        Route::get('show_premium_quotes_iframe/{id}','Quote\PremiumController@showPremiIframe');
        Route::post('save','Quote\PremiumController@submitQuotePremi');
        Route::post('save_premium_warranty','Quote\PremiumController@submitPremiInstallment');
        Route::get('create_premium_quotes/{id}','Quote\PremiumController@createPremium');
        Route::get('create_premium_warranty/{id}','Quote\PremiumController@createPremiumWarranty');
        Route::post('update_premium_quotes','Quote\PremiumController@updatePremium');
        Route::post('update_premium_quotes_onchange','Quote\PremiumController@updatePremiumOnchange');
        Route::post('create_initial_additional_premium',function(\Illuminate\Http\Request $request){
            $a = \App\QuotesAdditional::create([
                'type_' => '',
                'premium_type' => '',
                'annual_premium' => 0,
                'premium_table_id' => $request->data
            ]);
            return response()
                ->json([
                    'success' => true,
                    'pid' => intval($a->premium_table_id),
                    'id' => $a->id
                ]);
        });
        Route::post('update_hm_premium_quotes','Quote\PremiumController@updateHMPremium');
        Route::post('delete_additional_premium','Quote\PremiumController@deleteAdditionalPremium');
        Route::post('delete_v_premium','Quote\PremiumController@deleteVPremium');
        Route::post('delete_premium_warranty','Quote\PremiumController@deletePremiumWarranty');
    });
});

Route::prefix('inv')->group(function(){
    Route::prefix('notes')->group(function(){
        Route::get('create_credit_note/{id}','CreditNoteController@create');
        Route::post('store_credit_note','CreditNoteController@store');
        Route::get('show/{id}','CreditNoteController@show');
        Route::post('change_credit_note_vessels','CreditNoteController@changeCN');
        Route::post('new_cn_delete_old/{id}','CreditNoteController@NewCNDeleteOld');
    });

    Route::resource('invoice','Invoice\InvoiceController');
    Route::get('create_endorsement/{id}','InvoiceController@createEndorsement');
    Route::post('get_past_endorsement','AjaxController@getVesselPastData');
    Route::post('store_vessel_endorsement','EndorsementController@storeEndorsement');

    Route::get('premi_endorsement/{id}','EndorsementController@premiEndorsement');
    Route::post('update_premium_endorsement','EndorsementController@updatePremium');

    Route::get('endorsements_list','EndorsementController@index');
    Route::get('new_endorsement','EndorsementController@create');
    Route::post('request_data_invoice','AjaxController@reqInvData');
});
/** Sys */
Route::prefix('sys')->group(function(){
    Route::resource('assured','AssuredController');
    Route::get('assured_search',function(){
        $data = \App\Assured::where('assured_name','like','%'.strip_tags($_GET['query']).'%')
            ->where('status',1)
            ->paginate(10);
        return view('pib.assured',compact('data'));
    });
    Route::resource('manage_user','UsersController');
    Route::resource('manage_type','TypeController');
    Route::resource('item_quo','ItemQuoController');
    Route::resource('type_quo','TypeQuoController');
    Route::resource('channel','ChannelController');
    Route::get('channel-search','ChannelController@search');
    Route::resource('coa','CoaController');
    Route::resource('currency','CurrencyController');
    Route::resource('banks','BankController');
    Route::resource('insurer','Insurer\InsurerController');
    Route::prefix('insurer')->group(function(){
        Route::get('vessels/search_rows','VesselController@search');
        Route::post('vessel_detail','Vessel\VesselController@vesselDetail');
        Route::get('vessel_endorsement_view/{id}','EndorsementController@viewEndorsement');
        Route::get('vessel_endorsement_create_detail/{id}','EndorsementController@createVesselEndorsement');
        Route::get('vessel_endorsement_create/{id}','EndorsementController@createEndorsement');
        Route::post('vessel_endorsement_store','EndorsementController@storeEndorsement');
        Route::view('store_endorsement_redirect','pib.vessels.Endorsement.redirect');
        Route::post('check_insured_name','AjaxController@check_insured_name');
    });
});

Route::prefix('voucher')->group(function(){
    Route::resource('premium_receipt_voucher','Voucher\ReceiptVoucherController');
    Route::resource('premium_payment_voucher','Voucher\PaymentVoucherController');
    Route::post('create_premium_payment','Voucher\VoucherController@createPremiumPayment');
    Route::post('request_detail','Voucher\VoucherController@requestDetail');
    Route::post('request_detail_installment','Voucher\VoucherController@requestDetailInstallment');
    Route::get('payment/before-create','Voucher\VoucherController@beforeCreatePV');
    Route::post('payment/get_receipt_voucher','Voucher\VoucherController@getReceiptVoucher');
});

/**
 * Special
 */
Route::prefix('special')->group(function(){
   Route::get('direct-invoice/create','SpecialController@create');
    Route::post('quote-ref-check','SpecialController@quoteRefCheck');
   Route::post('direct-invoice/store','SpecialController@store');
    Route::post('get_insurer_detail','SpecialController@getInsurerDetail');

    Route::get('direct-invoice/premium/{id}','SpecialController@premium');
    Route::get('direct-invoice/installment/{id}','SpecialController@installment');
    Route::post('direct-invoice/installment_go','SpecialController@installment_go');
});

/** Intermediary */
Route::get('intermediary_broker_list','IntermediaryController@brokerList');
Route::get('intermediary_broker_edit/{id}','IntermediaryController@brokerEdit');
Route::get('intermediary_broker_create','IntermediaryController@brokerCreate');
Route::post('intermediary_broker_store','IntermediaryController@brokerStore');
Route::post('intermediary_broker_update','IntermediaryController@brokerUpdate');
Route::get('intermediary_broker_delete/{id}','IntermediaryController@brokerDelete');

Route::get('intermediary_finder_list','IntermediaryController@finderList');
Route::get('intermediary_finder_edit/{id}','IntermediaryController@finderEdit');
Route::get('intermediary_finder_create','IntermediaryController@finderCreate');
Route::post('intermediary_finder_store','IntermediaryController@finderStore');
Route::post('intermediary_finder_update','IntermediaryController@finderUpdate');
Route::get('intermediary_finder_delete/{id}','IntermediaryController@finderDelete');
Route::get('intermediary_list/search_rows','IntermediaryController@search');

/** Company vessel */

Route::post('get_sales_or_marketing',function(\Illuminate\Http\Request $request){
    $data = \App\ChannelGroup::where('type_',$request->channel)
        ->where('status',1)
        ->get();

    return response()
        ->json($data);
});

Route::post('store_new_company_ajax','AjaxController@store_new_company_ajax');


/** Incomes */
Route::get('incomes_list','IncomesController@index');

/** Clients */
Route::get('clients_list','ClientsController@index');
Route::get('create_new_client','ClientsController@createClient');
Route::get('client_edit/{id}','ClientsController@editClient');
Route::post('store_new_client','ClientsController@storeClient');
Route::post('update_client/{id}','ClientsController@updateClient');
Route::post('request_client_insureds','ClientsController@requestClientInsured');
Route::post('clients_list/request_client_insureds','ClientsController@requestClientInsured');

Route::get('clients_list/search_rows','ClientsController@search');

/** Search */

/** Change Password */
Route::view('change-password','pib.change_pass');

Route::get('show_hm_premium_quotes/{id}','ContentController@showHMPremi');
Route::get('show_premium_cargo/{id}','ContentController@showCargoPremi');

Route::post('acc/get_accounting_menu',function(){
   $data = \App\QuoteTypes::whereNotIn('group_name',['QUO','INV'])
       ->get();

    return response()

resources/views/pib/assured.blade.php
@extends('layouts.pib')
@section('content')
    <!-- MAIN -->
    <div class="main">
        <!-- MAIN CONTENT -->
        <div class="main-content">
            <div class="container-fluid">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <h3 class="page-title"><a type="button" href="{{ route('assured.create') }}" class="btn btn-default"><i class="fa fa-plus-square"></i> New Assured </a></h3>
                <div class="row">
                    <div class="col-md-10">
                        <!-- BORDERED TABLE -->
                        <div class="panel">
                            <div class="panel-heading">
                                <h3 class="panel-title">Assured</h3>
                                <div class="pull-right">
                                    <form method="get" class="form-inline" action="{{ url('assured_search') }}">
                                        <input type="text" class="form-control" name="query" @if(isset($_GET['query'])) value="{{ $_GET['query'] }}" @endif placeholder="search....">
                                        <button type="submit" class="btn btn-default"><span class="fa fa-search"></span> </button>
                                    </form>
                                    <br>
                                </div>
                            </div>
                            <div class="panel-body" >
                                <table class="table table-bordered table-responsive">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Assured Name</th>
                                        <th>Address</th>
                                        <th>Description</th>
                                        <th>NPWP</th>
                                        <th>Phone</th>
                                        <th>Fax</th>
                                        <th>Email</th>
                                        <th>Website</th>
                                        <th>Brokerage</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($data as $i => $d)
                                        <tr>
                                            <td>{{ $i + 1}}</td>
                                            <td>{{ $d->assured_name }}</td>
                                            <td>{{ $d->address }}</td>
                                            <td><small>{{ $d->description }}</small></td>
                                            <td>{{ $d->npwp }}</td>
                                            <td>{{ $d->phone }}</td>
                                            <td>{{ $d->fax }}</td>
                                            <td>{{ $d->email }}</td>
                                            <td>{{ $d->website }}</td>
                                            <td>{{ $d->brokerage }}%</td>
                                            <td>
                                                <div class="btn-group">
                                                    <a class="btn btn-primary" href="{{ route('assured.edit',$d->id) }}"><span class="fa fa-edit"></span></a>
                                                    <form method="POST" action="{{ route('assured.destroy',$d->id)  }}'" style="display:inline">
                                                        <input name="_method" type="hidden" value="DELETE">
                                                        <input name="_token" type="hidden" value=" {{ csrf_token() }}">
                                                        <button type="submit" class="btn btn-danger"><span class="fa fa-trash"></span></button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                {{ $data->render() }}
                            </div>
                        </div>
                        <!-- END BORDERED TABLE -->
                    </div>
                </div>
            </div>
        </div>
        <!-- END MAIN CONTENT -->
    </div>

    <!-- END MAIN -->
@endsection

resources/views/pib/assured_create.blade.php
@extends('layouts.pib')
@section('content')
    <!-- MAIN -->
    <div class="main">
        <!-- MAIN CONTENT -->
        <div class="main-content">
            <div class="container-fluid">
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <h4 class="page-title">Add New Assured</h4>
                {!! Form::open(array('route' => 'assured.store','method'=>'POST','enctype'=>'multipart/form-data')) !!}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Assured Name</label>
                            <input type="text" class="form-control" name="assured_name" required="">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Address</label>
                            <textarea class="form-control" name="address" rows="3"></textarea>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Description</label>
                            <textarea class="form-control" name="description" rows="3"></textarea>
                        </div>
                        <div class="form-group">
                            <label class="control-label">NPWP</label>
                            <input type="text" class="form-control" name="npwp" required="">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Phone</label>
                            <input type="text" class="form-control" name="text" required="">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Fax</label>
                            <input type="text" class="form-control" name="fax" required="">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Email</label>
                            <input type="email" class="form-control" name="email" required="">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Website</label>
                            <input type="text" class="form-control" name="website" required="">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Brokerage</label>
                            <div class="input-group">
                                <input type="text" class="form-control" name="brokerage" required="">
                                <span class="input-group-addon">%</span>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
        <!-- END MAIN CONTENT -->
    </div>
    <!-- END MAIN -->

@endsection

resources/views/pib/assured_edit.blade.php
@extends('layouts.pib')
@section('content')
    <!-- MAIN -->
    <div class="main">
        <!-- MAIN CONTENT -->
        <div class="main-content">
            <div class="container-fluid">
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <h4 class="page-title">Edit Assured</h4>
                    {!! Form::model($data, ['method' => 'PATCH','route' => ['assured.update', $data->id], 'enctype'=>'multipart/form-data']) !!}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Assured Name</label>
                            <input type="text" class="form-control" name="assured_name" value="{{ $data->assured_name }}">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Address</label>
                            <textarea class="form-control" name="address" rows="3">{{ $data->address }}</textarea>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Description</label>
                            <textarea class="form-control" name="description" rows="3">{{ $data->description }}</textarea>
                        </div>
                        <div class="form-group">
                            <label class="control-label">NPWP</label>
                            <input type="text" class="form-control" name="npwp" value="{{ $data->npwp }}">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Phone</label>
                            <input type="text" class="form-control" name="text" value="{{ $data->phone }}">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Fax</label>
                            <input type="text" class="form-control" name="fax" value="{{ $data->fax }}">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Email</label>
                            <input type="email" class="form-control" name="email" value="{{ $data->email }}">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Website</label>
                            <input type="text" class="form-control" name="website" value="{{ $data->website }}">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Brokerage</label>
                            <div class="input-group">
                                <input type="text" class="form-control" name="brokerage" required="" value="{{ $data->brokerage }}">
                                <span class="input-group-addon">%</span>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
        <!-- END MAIN CONTENT -->
    </div>
    <!-- END MAIN -->

@endsection

resources/views/pib/coa_create.blade.php
@extends('layouts.pib')
@section('content')
        <!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <h4 class="page-title">Coa Create</h4>
            <form method="post" action="{{ route('coa.store') }}">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Code</label>
                                <input type="text" name="code" class="form-control" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Description</label>
                                <input type="text" name="description" class="form-control" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 ">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-md">Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
<!-- /.container-fluid-->



@endsection

resources/views/pib/coa_edit.blade.php
@extends('layouts.pib')
@section('content')
        <!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <h4 class="page-title">Coa Create</h4>
            <form method="post" action="{{ route('coa.update',$data->id) }}">
                <input type="hidden" name="_method" value="PATCH">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Code</label>
                                <input type="text" name="code" class="form-control" value="{{ $data->code }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Description</label>
                                <input type="text" name="description" class="form-control" value="{{ $data->description }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 ">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-md">Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
<!-- /.container-fluid-->



@endsection

resources/views/pib/home.blade.php
@extends('layouts.pib')
@section('content')
    <div class="main">
        <!-- MAIN CONTENT -->
        <div class="main-content">
            <div class="container-fluid">
                <!-- OVERVIEW -->
            </div>
        </div>
        <!-- END MAIN CONTENT -->
    </div>
@endsection

resources/views/pib/intermediary_finder_edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Irman
 * Date: 8/3/2018
 * Time: 4:46 PM
 */

resources/views/pib/users.blade.php
@extends('layouts.pib')
@section('content')
    <!-- MAIN -->
    <div class="main">
        <!-- MAIN CONTENT -->
        <div class="main-content">
            <div class="container-fluid">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <h3 class="page-title"><a type="button" href="{{ route('manage_user.create') }}" class="btn btn-default"><i class="fa fa-plus-square"></i> New User </a></h3>
                <div class="row">
                    <div class="col-md-12">
                        <!-- BORDERED TABLE -->
                        <div class="panel">
                            <div class="panel-heading">
                                <h3 class="panel-title">Users</h3>
                            </div>
                            <div class="panel-body">
                                <table class="table table-bordered data-table">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Departement</th>
                                        <th>Hak Akses</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($data as $i => $d)
                                        @if($d->id != Auth::id())
                                        <tr>
                                            <td>{{ $i + 1}}</td>
                                            <td>{{ $d->name }}</td>
                                            <td>{{ $d->email }}</td>
                                            <td>{{ $d->departement }}</td>
                                            <td>{{ $d->hak_akses }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <a class="btn btn-primary" href="{{ route('manage_user.edit',$d->id) }}"><span class="fa fa-edit"></span></a>
                                                    <form method="POST" action="{{ route('manage_user.destroy',$d->id)  }}'" style="display:inline">
                                                        <input name="_method" type="hidden" value="DELETE">
                                                        <input name="_token" type="hidden" value="'.csrf_token().'">
                                                        <button type="submit" class="btn btn-danger"><span class="fa fa-trash"></span></button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                        @endif
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- END BORDERED TABLE -->
                    </div>
                </div>
            </div>
        </div>
        <!-- END MAIN CONTENT -->
    </div>

    <!-- END MAIN -->
@endsection