routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/','HomeController@index');
Route::get('reports','ReportController@index');


Route::prefix('quotation')->group(function(){
    Route::resource('quote','Quote\QuoteController');
    Route::post('save_temporary_quote','Quote\HelperController@saveTemporaryQuote');
    Route::post('brokerage_count','Quote\HelperController@brokerage_count');
    Route::post('new_quote_delete_old','Quote\HelperController@action_quote_new');
    Route::get('send_invoice/{id}','Quote\HelperController@sendInvoice');
    Route::get('quotes_draft','Quote\HelperController@quotesDraft');
    Route::post('quotes_publish/{id}',function(\Illuminate\Http\Request $request,$id){
        \App\Quotes::find($id)
            ->update([
                'finish' => 1
            ]);

        return redirect()->route('quote.index')
            ->with('success','publish new quote : success');
    });
    Route::post('save_draft_quote','AjaxController@saveDraft');
    Route::get('quotes_draft_delete/{id}',function($id){
        \App\Quotes::where('id',$id)->update(['is_deleted' => 1]);
        return redirect('quotation/quotes_draft')
            ->with('success','Quote deleted');
    });
    Route::post('get_prorata_days','AjaxController@getProrataDays');
    Route::post('is_approve_quote',function(\Illuminate\Http\Request $request){
        $stats = ['granted','approve'];
        \App\Quotes::find($request->id)
            ->update(['status' => $stats[$request->approve]]);
    });
    Route::get('get_company_assured',function(){
        $data = \App\Insurer::all();
        return response()
            ->json(['data' => $data]);
    });
    Route::post('get_valid_until','AjaxController@getValidUntil');
    Route::post('request_vessel_items','AjaxController@getVesselItems');
    Route::post('request_vessels_detail','AjaxController@getVesselsDetail');
    Route::post('insert_new_vessel','AjaxController@storeVessel');
    Route::prefix('premium')->group(function(){
        Route::get('show_premium_quotes/{id}','Quote\PremiumController@showPremi');
        Route::get('show_premium_quotes_iframe/{id}','Quote\PremiumController@showPremiIframe');
        Route::post('save','Quote\PremiumController@submitQuotePremi');
        Route::post('save_premium_warranty','Quote\PremiumController@submitPremiInstallment');
        Route::get('create_premium_quotes/{id}','Quote\PremiumController@createPremium');
        Route::get('create_premium_warranty/{id}','Quote\PremiumController@createPremiumWarranty');
        Route::post('update_premium_quotes','Quote\PremiumController@updatePremium');
        Route::post('update_premium_quotes_onchange','Quote\PremiumController@updatePremiumOnchange');
        Route::post('create_initial_additional_premium',function(\Illuminate\Http\Request $request){
            $a = \App\QuotesAdditional::create([
                'type_' => '',
                'premium_type' => '',
                'annual_premium' => 0,
                'premium_table_id' => $request->data
            ]);
            return response()
                ->json([
                    'success' => true,
                    'pid' => intval($a->premium_table_id),
                    'id' => $a->id
                ]);
        });
        Route::post('update_hm_premium_quotes','Quote\PremiumController@updateHMPremium');
        Route::post('delete_additional_premium','Quote\PremiumController@deleteAdditionalPremium');
        Route::post('delete_v_premium','Quote\PremiumController@deleteVPremium');
        Route::post('delete_premium_warranty','Quote\PremiumController@deletePremiumWarranty');
    });
});

Route::prefix('inv')->group(function(){
    Route::prefix('notes')->group(function(){
        Route::get('create_credit_note/{id}','CreditNoteController@create');
        Route::post('store_credit_note','CreditNoteController@store');
        Route::get('show/{id}','CreditNoteController@show');
        Route::post('change_credit_note_vessels','CreditNoteController@changeCN');
        Route::post('new_cn_delete_old/{id}','CreditNoteController@NewCNDeleteOld');
    });

    Route::resource('invoice','Invoice\InvoiceController');
    Route::get('create_endorsement/{id}','InvoiceController@createEndorsement');
    Route::post('get_past_endorsement','AjaxController@getVesselPastData');
    Route::post('store_vessel_endorsement','EndorsementController@storeEndorsement');

    Route::get('premi_endorsement/{id}','EndorsementController@premiEndorsement');
    Route::post('update_premium_endorsement','EndorsementController@updatePremium');

    Route::get('endorsements_list','EndorsementController@index');
    Route::get('new_endorsement','EndorsementController@create');
    Route::post('request_data_invoice','AjaxController@reqInvData');
});
/** Sys */
Route::prefix('sys')->group(function(){
    Route::resource('assured','AssuredController');
    Route::get('assured_search',function(){
        $data = \App\Assured::where('assured_name','like','%'.strip_tags($_GET['query']).'%')
            ->where('status',1)
            ->paginate(10);
        return view('pib.assured',compact('data'));
    });
    Route::resource('manage_user','UsersController');
    Route::resource('manage_type','TypeController');
    Route::resource('item_quo','ItemQuoController');
    Route::resource('type_quo','TypeQuoController');
    Route::resource('channel','ChannelController');
    Route::get('channel-search','ChannelController@search');
    Route::resource('coa','CoaController');
    Route::resource('currency','CurrencyController');
    Route::resource('banks','BankController');
    Route::resource('insurer','Insurer\InsurerController');
    Route::prefix('insurer')->group(function(){
        Route::get('vessels/search_rows','VesselController@search');
        Route::post('vessel_detail','Vessel\VesselController@vesselDetail');
        Route::get('vessel_endorsement_view/{id}','EndorsementController@viewEndorsement');
        Route::get('vessel_endorsement_create_detail/{id}','EndorsementController@createVesselEndorsement');
        Route::get('vessel_endorsement_create/{id}','EndorsementController@createEndorsement');
        Route::post('vessel_endorsement_store','EndorsementController@storeEndorsement');
        Route::view('store_endorsement_redirect','pib.vessels.Endorsement.redirect');
        Route::post('check_insured_name','AjaxController@check_insured_name');
    });
});

Route::prefix('voucher')->group(function(){
    Route::resource('premium_receipt_voucher','Voucher\ReceiptVoucherController');
    Route::resource('premium_payment_voucher','Voucher\PaymentVoucherController');
    Route::post('create_premium_payment','Voucher\VoucherController@createPremiumPayment');
    Route::post('request_detail','Voucher\VoucherController@requestDetail');
    Route::post('request_detail_installment','Voucher\VoucherController@requestDetailInstallment');
    Route::get('payment/before-create','Voucher\VoucherController@beforeCreatePV');
    Route::post('payment/get_receipt_voucher','Voucher\VoucherController@getReceiptVoucher');
});

/**
 * Special
 */
Route::prefix('special')->group(function(){
   Route::get('direct-invoice/create','SpecialController@create');
    Route::post('quote-ref-check','SpecialController@quoteRefCheck');
   Route::post('direct-invoice/store','SpecialController@store');
    Route::post('get_insurer_detail','SpecialController@getInsurerDetail');

    Route::get('direct-invoice/premium/{id}','SpecialController@premium');
    Route::get('direct-invoice/installment/{id}','SpecialController@installment');
    Route::post('direct-invoice/installment_go','SpecialController@installment_go');
});

/** Intermediary */
Route::get('intermediary_broker_list','IntermediaryController@brokerList');
Route::get('intermediary_broker_edit/{id}','IntermediaryController@brokerEdit');
Route::get('intermediary_broker_create','IntermediaryController@brokerCreate');
Route::post('intermediary_broker_store','IntermediaryController@brokerStore');
Route::post('intermediary_broker_update','IntermediaryController@brokerUpdate');
Route::get('intermediary_broker_delete/{id}','IntermediaryController@brokerDelete');

Route::get('intermediary_finder_list','IntermediaryController@finderList');
Route::get('intermediary_finder_edit/{id}','IntermediaryController@finderEdit');
Route::get('intermediary_finder_create','IntermediaryController@finderCreate');
Route::post('intermediary_finder_store','IntermediaryController@finderStore');
Route::post('intermediary_finder_update','IntermediaryController@finderUpdate');
Route::get('intermediary_finder_delete/{id}','IntermediaryController@finderDelete');
Route::get('intermediary_list/search_rows','IntermediaryController@search');

/** Company vessel */

Route::post('get_sales_or_marketing',function(\Illuminate\Http\Request $request){
    $data = \App\ChannelGroup::where('type_',$request->channel)
        ->where('status',1)
        ->get();

    return response()
        ->json($data);
});

Route::post('store_new_company_ajax','AjaxController@store_new_company_ajax');


/** Incomes */
Route::get('incomes_list','IncomesController@index');

/** Clients */
Route::get('clients_list','ClientsController@index');
Route::get('create_new_client','ClientsController@createClient');
Route::get('client_edit/{id}','ClientsController@editClient');
Route::post('store_new_client','ClientsController@storeClient');
Route::post('update_client/{id}','ClientsController@updateClient');
Route::post('request_client_insureds','ClientsController@requestClientInsured');

app/Insurer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Insurer extends Model
{
    protected $table = 'insurer';
    protected $primaryKey = 'id';
    protected $fillable = [
        'insured', 'address', 'phone', 'email', 'channel', 'channel_id', 'pic','status'
    ];

    public function Broker()
    {
        return $this->belongsTo('App\ChannelGroup','channel_id');
    }

    public function Vessels()
    {
        return $this->hasMany('App\Vessels','insurer_id');
    }
}

app/Http/Controllers/Insurer/InsurerController.php
<?php

namespace App\Http\Controllers\Insurer;

use App\Http\Controllers\BaseController;
use App\Insurer;
use App\Vessels;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class InsurerController extends BaseController
{
    public function __construct()
    {
        $this->middleware('admin1');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Insurer::orderBy('id','Desc')
            ->where('status',1)
            ->paginate(10);
        return view('pib.insurer.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pib.insurer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Insurer::create($request->post());
        $id = Insurer::orderBy('id','DESC')
            ->first()
            ->id;
        foreach($request->vessel_name as $i => $val){
            Vessels::create([
                'vessel_name' => $val,
                'vessel_type' => $request->vessel_type[$i],
                'built' => $request->built[$i],
                'gt' => $request->gt[$i],
                'flag' => $request->flag[$i],
                'class' => $request->class[$i],
                'crew' => $request->crew[$i],
                'port_of_registry' => $request->port_of_registry[$i],
                'trading' => $request->trading[$i],
                'term' => $request->term[$i],
                'insurer_id' => $id
            ]);
        }
        return redirect()->route('insurer.index')
            ->with('success','Add new insurer company success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = insurer::find($id);
        $detail = Vessels::where('insurer_id',$id)
            ->where('status',1)
            ->get();

        return view('pib.insurer.edit',compact('data','detail'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Insurer::find($request->vessel_id)
            ->update($request->all());
        Vessels::where('insurer_id',$request->vessel_id)
            ->update(['status' => 0]);
        foreach ($request->vessel_name as $i => $val) {
            if(isset($request->id_v[$i])){
                Vessels::find($request->id_v[$i])
                    ->update([
                        'vessel_name' => $val,
                        'vessel_type' => $request->vessel_type[$i],
                        'built' => isset($request->built[$i]) ? $request->built[$i] : 0,
                        'gt' => isset($request->gt[$i]) ? $request->gt[$i] : 0,
                        'flag' => $request->flag[$i],
                        'class' => $request->class[$i],
                        'crew' => $request->crew[$i],
                        'port_of_registry' => $request->port_of_registry[$i],
                        'trading' => $request->trading[$i],
                        'term' => $request->term[$i],
                        'insurer_id' => $request->vessel_id,
                        'status' => 1
                    ]);
            }else{
                Vessels::create([
                    'vessel_name' => $val,
                    'vessel_type' => $request->vessel_type[$i],
                    'built' => isset($request->built[$i]) ? $request->built[$i] : 0,
                    'gt' => isset($request->gt[$i]) ? $request->gt[$i] : 0,
                    'flag' => $request->flag[$i],
                    'class' => $request->class[$i],
                    'crew' => $request->crew[$i],
                    'port_of_registry' => $request->port_of_registry[$i],
                    'trading' => $request->trading[$i],
                    'term' => $request->term[$i],
                    'insurer_id' => $request->vessel_id
                ]);
            }

        }

        return redirect()->route('insurer.index')
            ->with('success','data updated.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Insurer::find($id)
            ->update([
                'status' => 0
            ]);
        Vessels::where('insurer_id',$id)
            ->update(['status' => 0]);
        return redirect()->route('insurer.index')
            ->with('success','Data deleted.');
    }
}

resources/views/pib/insurer/index.blade.php
@extends('layouts.pib')
@section('content')
    <style>
        table.ndj{
            margin: -8px;
            width: 103% !important;
        }

        table.ndj td{
            padding:8px;
        }
    </style>
    <!-- MAIN -->
    <div class="main">
        <!-- MAIN CONTENT -->
        <div class="main-content">
            <div class="container-fluid">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <h3 class="page-title"><a type="button" href="{{ route('insurer.create') }}" class="btn btn-default"><i class="fa fa-plus-square"></i> New Insured Company </a></h3>
                <div class="row">
                    <div class="col-md-12">
                        <!-- BORDERED TABLE -->
                        <div class="panel">
                            <div class="panel-heading">
                                <h3 class="panel-title">Insured Company</h3>
                                <div class="pull-right">
                                    <form method="get" class="form-inline" action="{{ url('sys',['insurer','search_rows']) }}">
                                        <input type="text" class="form-control" name="query" @if(isset($query)) value="{{ $query }}" @endif placeholder="search....">
                                        <button type="submit" class="btn btn-default"><span class="fa fa-search"></span> </button>
                                    </form>
                                    <br>
                                </div>
                            </div>
                            <div class="panel-body">
                                <table class="table table-bordered data-table table-striped">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Company</th>
                                        <th>Address</th>
                                        <th>Phone</th>
                                        <th>Email</th>
                                        <th>Channel</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($data as $i => $d)
                                        <tr>
                                            <td>{{ $i + 1}}</td>
                                            <td>{{ $d->insured }}  @if(isset($_GET['query'])) {!! (\App\Http\Controllers\VesselController::is_in_vessel($d->id,strip_tags($_GET['query']))) ? ' <i class="fa fa-ship" title="Ditemukan di daftar kapal."></i>' : '' !!} @endif</td>
                                            <td><small>{{ $d->address }}</small></td>
                                            <td>{{ $d->phone }}</td>
                                            <td>{{ $d->email }}</td>
                                            <td>{{ $d->channel }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <a class="btn btn-default btn-sm" onclick="viewDetail({{ $d->id }})"><span class="fa fa-eye-slash"></span></a> <a class="btn btn-primary btn-sm" href="{{ route('insurer.edit',$d->id) }}"><span class="fa fa-pencil"></span></a> <form method="post" id="company-{{ $d->id }}" style="display:inline;" action="{{ route('insurer.destroy',$d->id) }}">{{ csrf_field() }} <input type="hidden" name="_method" value="DELETE"> <a class="btn btn-danger btn-sm" onclick="event.preventDefault(); document.getElementById('company-{{ $d->id }}').submit();"><span class="fa fa-trash"></span></a></form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                {{ $data->appends($_GET)->links() }}
                            </div>
                        </div>
                        <!-- END BORDERED TABLE -->
                    </div>
                </div>
            </div>
        </div>
        <!-- END MAIN CONTENT -->
    </div>
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Vessel Detail</h4>
                </div>
                <div class="modal-body">
                    <div class="detail_broker"></div>
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>Vessel Name</th>
                            <th>Vessel Type</th>
                            <th>Built</th>
                            <th>GT</th>
                            <th>flag</th>
                            <th>Class</th>
                            <th>Crew</th>
                            <th>Port of Registry</th>
                            <th>Cargo</th>
                            <th>Trading</th>
                            <th>Term</th>
                            <!--
                            <th>endorsement</th>
                            !-->
                        </tr>
                        </thead>
                        <tbody class="vessels_table_content">

                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div>
    </div>
    <script>
        function viewDetail(id){
            $("#myModal").modal('show');
            $('.modal-footer').html("");
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type: 'post',
                url: '{!! url('sys',['insurer','vessel_detail']) !!}',
                data: {id: id},
                success: function (data) {
                    $(".detail_broker").html(
                            '<table class="table" style="border: none;font-weight:600;"> ' +
                            '<tr><td>Channel</td><td>:</td><td>'+data.channel.channel+'</td></tr> ' +
                            '<tr><td>Marketing</td><td>:</td><td>'+data.channel.name+'</td></tr> ' +
                            '<tr><td>PIC</td><td>:</td><td>'+data.channel.pic+'</td></tr>' +
                            '</table><hr>'
                    );
                    $('.vessels_table_content').html("");
                    $.each(data.data,function(i,val){
                        var html = '<tr><td>'+parseInt(i + 1)+'</td><td>'+val.vessel_name+'</td><td>'+val.vessel_type+'</td><td>'+val.built+'</td><td>'+val.gt+'</td><td>'+val.flag+'</td><td>'+val.class+'</td><td>'+val.crew+'</td><td>'+val.port_of_registry+'</td><td>'+val.cargo+'</td><td>'+val.trading+'</td><td>'+val.term+'</td></tr>';
                        $('.vessels_table_content').append(html);
                    });
                    $('.modal-footer').append('<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>')
                }
            })
        }

        $(".btn-danger").click(function(){
            if(!confirm('are you sure?')){
                return false;
            }
        })
    </script>
    <!-- END MAIN -->
@endsection